title: Attila Ficsor
logo: /assets/img/attilaficsor.jpg
description: Computer scientist, PhD Student
website1: https://ftsrg.mit.bme.hu/
affiliation1: Critical Systems Research Group
title1: PhD Student
scholar: GY5_AzUAAAAJ
mail: attila.ficsor@edu.bme.hu
linkedin: attilaficsor
theme: jekyll-theme-minimal
